### PR TITLE
Only upgrade changed files

### PR DESCRIPTION
**Pull request by jakirkham**
Only upgrade files if they have changed. Otherwise skip over the unchanged file and try the next one. This is a similar change as had occurred with updating in commit ( https://github.com/jayfk/statuspage/commit/a2b99b2903fc0b4793065b634bb9a5043b9f1a6a ).

EDIT: Have tried this locally and it works. However, am having some trouble getting it to work with the test suite.

### CODE REVIEW

**Comment by jakirkham** [comment]
This probably needs some tweaks. If you have a chance to advise, that would be very much appreciated, @jayfk .

**Comment by jakirkham** [comment]
This probably needs some tweaks. If you have a chance to advise, that would be very much appreciated, @jayfk .

**Comment by jayfk** [comment]
> EDIT: Have tried this locally and it works. However, am having some trouble getting it to work with the test suite.

Nevermind, the tests are broken right now. I'll have a look at it.

**Comment by jakirkham** [comment]
Ok, thanks @jayfk .

**Comment by jakirkham** [comment]
Out of curiosity, any idea when this might show up in a release? No rush or anything just trying to get an idea.

**Pull request merged**
